default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_demo_aug_development
test: &test
  <<: *default
  database: rails_demo_aug_test
  username: rails_demo_aug
  password: <%= ENV['RAILS_DEMO_AUG_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: rails_demo_aug_production
  username: rails_demo_aug
  password: <%= ENV['RAILS_DEMO_AUG_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
